#!/bin/bash
git add . # tiek pieteiktas adreses "uzmanīšanai"
git config --global user.name edgaars
git config --global user.email mezajevsedgars@inbox.lv
#git commit -m "Class_04"
git commit -m "Class_$1"
git push origin main
